#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'



# ________________Custom Configs_______________________________


# Load Custom Script..
sh ~/system_configurations_arch/dotfiles/system_utilities/remaining_days

# customs
#PS1='[\u@\h \W]\$ '
PS1=' \u : \W : $ '



# Custom Scripts
export PATH=$PATH:~/system_utils

# OTHER Binaries Directory
OTHER_BINARIES_DIR="$HOME/other_binaries"

# Custom Aliases
alias notes='$OTHER_BINARIES_DIR/FuzPad/bin/fuzpad'
alias rr='$OTHER_BINARIES_DIR/RustRover/RustRover-2024.3.4/bin/rustrover'


alias a=Hyprland
alias cat="bat"
alias ls="lsd"
alias l="lsd -l"
alias fm=yazi
alias hx=helix


# Custom Binaries
export PATH=$PATH:~/directly_executable_binaries

# Cargo/Rust & Ziglang's Custom Build Target
export CARGO_TARGET_DIR=/tmp/cargo-target
alias zig_build="zig build --cache-dir /tmp/zig-cache"
alias zig_run="zig run src/main.zig --cache-dir /tmp/zig-cache"

# Flutter , Dart installed using Vscode Extension i.e Flutter Extension
export PATH="$PATH:/home/user_1/.flutterSDK/flutter/bin"


#################################################################
# Auto Generated By Other Programs


