#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'



# ________________Custom Configs_______________________________


# Load Custom Script..
sh ~/system_configurations_arch/dotfiles/system_utilities/remaining_days

# customs
#PS1='[\u@\h \W]\$ '
PS1=' \u : \W : $ '



# Custom Scripts
export PATH=$PATH:~/system_utils

# OTHER Binaries Directory
OTHER_BINARIES_DIR="$HOME/other_binaries"

# Custom Aliases
alias telegram='$OTHER_BINARIES_DIR/Telegram/Telegram'
alias a=Hyprland
alias ls="lsd -l"
alias fm=yazi

# Flatpak
alias firefox='flatpak run org.mozilla.firefox'
alias inkscape='flatpak run org.inkscape.Inkscape'
alias okular='flatpak run org.kde.okular'
alias signal='flatpak run org.signal.Signal'


# Custom Binaries
export PATH=$PATH:~/directly_executable_binaries

# Cargo/Rust & Ziglang's Custom Build Target
export CARGO_TARGET_DIR=/tmp/cargo-target
alias zig_build="zig build --cache-dir /tmp/zig-cache"
alias zig_run="zig run src/main.zig --cache-dir /tmp/zig-cache"

# Flutter , Dart installed using Vscode Extension i.e Flutter Extension
export PATH="$PATH:/home/user_1/.flutterSDK/flutter/bin"


#################################################################
# Auto Generated By Other Programs

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
. "$HOME/.cargo/env"
