#!/bin/bash

# Killing all Running instances of Hyprpaper..
pkill -f hyprpaper

# Run Random Wallpaper Script.. to generate random hyprpaper config file..
sh ~/.config/hypr/scripts/random_wallpapers.sh

# Start a New Instance of Hyprpaper in Background.. i.e background process.
#  Sometimes, running & alone doesn’t fully detach the process from the terminal session.
#  nohup will allow Hyprpaper to keep running even if you close the terminal:
# nohup: Prevents the process from stopping if the terminal session ends.
# > /dev/null 2>&1: Redirects both standard output and errors to /dev/null (so you don’t see any output).
nohup hyprpaper > /dev/null 2>&1 &

