#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'



# ________________Custom Configs_______________________________

# Greetings
echo "_____ Welcome Back , Boss ,,____________";
echo "___________Your Kingdom is Ready____________";

# customs
#PS1='[\u@\h \W]\$ '
PS1='\u : \W : $ '



# Custom Scripts
export PATH=$PATH:~/system_utils

# OTHER Binaries Directory
OTHER_BINARIES_DIR="$HOME/other_binaries"


# Flatpak
alias firefox='flatpak run org.mozilla.firefox'
alias inkscape='flatpak run org.inkscape.Inkscape'
alias okular='flatpak run org.kde.okular'
alias signal='flatpak run org.signal.Signal'


# Custom Aliases 
alias a=Hyprland
alias nvim='$OTHER_BINARIES_DIR/nvim-linux64/bin/nvim'


# Custom Binaries
export PATH=$PATH:~/custom_binaries

# Cargo Custom Build Target
export CARGO_TARGET_DIR=/tmp/cargo-target


#################################################################
# Auto Generated By Other Programs

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
. "$HOME/.cargo/env"
