#!/bin/bash



#185.228.168.10
#185.228.169.11

# Define the DNS entries to append
DNS_ENTRIES="nameserver 185.228.168.10 #CleanBrowsing (Adult Filter)
nameserver 185.228.169.11 # Secondary CleanBrowsing DNS"


# File to modify
RESOLV_CONF="/etc/resolv.conf"



# Check if the script is run as root
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root. Use sudo."
    exit 1
fi

# Append DNS entries if they are not already present
if ! grep -q "185.228.168.10" "$RESOLV_CONF"; then
    # Making Resolv.conf file mutable...
    chattr -i "$RESOLV_CONF"
    echo "Appending DNS entries to $RESOLV_CONF..."
    echo -e "$DNS_ENTRIES" >> "$RESOLV_CONF"
else
    echo "DNS entries already present in $RESOLV_CONF. Skipping append."
fi

# Make the file immutable
echo "Making $RESOLV_CONF immutable..."
chattr +i "$RESOLV_CONF"

# Confirm success
echo "DNS entries added and $RESOLV_CONF is now immutable."
