#!/bin/bash 

# Enable Flatpak
enable_flatpak(){
	grep -qxF "kernel.unprivileged_userns_clone=1" /etc/sysctl.conf || echo "kernel.unprivileged_userns_clone=1" | sudo tee -a /etc/sysctl.conf
	sudo sysctl -p
}


# Mount Hardisk
mount_hardisk(){
	# Create Mounting Point.
	sudo mkdir -p /media/disks/HardDisk
	lsblk
	echo "_____Enter HardDisk Name / Partition to Mount :-  "
	read harddisk_partition
	echo   $harddisk_partition
	sudo mount -t ext4 /dev/$harddisk_partition /media/disks/HardDisk
}

# Check if qbittorrent is running
start_qbittorrent(){
  if ! pgrep -x "qbittorrent" > /dev/null; then
    notify-send -u critical "Info" "Starting QBittorrent..." -t 10000
    setsid qbittorrent
else
    notify-send -u critical "Info" "QBittorrent is already running." -t 10000
  fi
}

# System update function
update_system(){
	notify-send -u critical "Info" "Updating System..." -t 10000
	sudo pacman -Syu
	# Updating AppImages
	notify-send -u critical "Info" "Updating AppImages..." -t 10000
	am -s
	am -u
	am reinstall
	notify-send -u critical "Info" "System Updated..." -t 10000
}


